### ISSUE TITLE
installing requirements

### ISSUE THREAD

**Issue by soupnatzi** [Zucccs/Mercury#7]
pip install -r requirements.txt 
Requirement already satisfied: colorama in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1)) (0.3.9)
Collecting hashlib (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/74/bb/9003d081345e9f0451884146e9ea2cff6e4cc4deac9ffd4a9ee98b318a49/hashlib-20081119.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 12, in <module>
        import setuptools.version
      File "/usr/local/lib/python2.7/dist-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 36, in <module>
        import email.parser
      File "/usr/lib/python2.7/email/parser.py", line 12, in <module>
        from email.feedparser import FeedParser
      File "/usr/lib/python2.7/email/feedparser.py", line 27, in <module>
        from email import message
      File "/usr/lib/python2.7/email/message.py", line 16, in <module>
        import email.charset
      File "/usr/lib/python2.7/email/charset.py", line 13, in <module>
        import email.base64mime
      File "/usr/lib/python2.7/email/base64mime.py", line 40, in <module>
        from email.utils import fix_eols
      File "/usr/lib/python2.7/email/utils.py", line 27, in <module>
        import random
      File "/usr/lib/python2.7/random.py", line 49, in <module>
        import hashlib as _hashlib
      File "hashlib.py", line 115, in <module>
        f()
    TypeError: 'frozenset' object is not callable
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-9ex4_k/hashlib/

**Comment by MetaChar** [comment]
try manually installing it 
`pip install hashlib`

**Comment by q2dg** [comment]
Well, this repo seems pretty abandoned... :-(

**Comment by MetaChar** [comment]
@q2dg this repo hasn't been updated in a while I'm busy with other repo's when I have time I will  eventually go back and fix my old repo's

**Comment by micahjmartin** [comment]
I'm sure @MetaChar would appreciate some pull requests if you really want to help out

**Comment by MetaChar** [comment]
@micahjmartin I would 😌

**Comment by micahjmartin** [comment]
It seems to be an issue with Hashlib and not Mercury. 

According to [this stackoverflow](https://stackoverflow.com/questions/38751800/python-2-7-on-os-x-typeerror-frozenset-object-is-not-callable-on-each-comman/40259767#40259767), there is a cached version of hashlib (`hashlib-20081119`) which appears to be the same version that is cached on your system. The stackoverflow shows how to removed the cached package and get a fresh version to install.

You may also have luck installing `hashlib` with `easy_install` or running pip with the `--no-cache-dir` flag.

Hope this helps you all! 😃

**Comment by shawsuraj** [comment]
Hashlib module is already installed by default in python2.5+ [(Check Here)](https://pypi.org/project/hashlib/).
